### ISSUE TITLE
how to set theme?

### ISSUE THREAD

**Issue by bryant-the-coder** [Manas140/Conscious#4]

**Comment by shufuwa** [comment]
if by theme you mean color scheme, then i do the following

1. create the `yourtheme.lua` inside `~/.config/nvim/lua/colors` dir (ex. https://github.com/Manas140/Conscious/blob/main/lua/colors/paradise-dark.lua)

2. edit the first line in `init.lua` and change the `_G.theme = "yourtheme"` (ex. `_G.theme = "paradise-dark"`)

3. restart nvim

**Comment by bryant-the-coder** [comment]
o.o

thx bud i always wanted to use base16 xD

**Comment by bryant-the-coder** [comment]
@shufuwa i wanna ask. i have a folder structure of lua/core/themes.lua

i want to set themes from themes.lua how would i do that?

**Comment by Manas140** [comment]
You may need to edit the path it retrieves theme from and also source the themes.lua before it is used to set the colorscheme

**Comment by bryant-the-coder** [comment]
hmm it cant work... i place my custom colors in a path... i tried but it cant retrieve it

**Comment by bryant-the-coder** [comment]
@Manas140 u can see my nvim repo... it is quite big as this. i cant seem to get to to work

**Comment by Manas140** [comment]
Add this plugin https://github.com/RRethy/nvim-base16 and follow it's configuration guide, well you did say you want to use base16. So, yea this would be good enough

**Comment by bryant-the-coder** [comment]
how to add my own highlightin then?

**Comment by Manas140** [comment]
Just configure those after setting up the colorscheme

**Comment by bryant-the-coder** [comment]
like in a dir?

**Comment by Manas140** [comment]
have a look at colors.lua

**Comment by bryant-the-coder** [comment]
i tried xD it didnt work
