### ISSUE TITLE
The colors doest not working, nvim still show its default color. 

### ISSUE THREAD

**Issue by AryAntara** [Manas140/Conscious#9]
my nvim only show its default color, i need to change colorscheme by select the colors but with this way. i cannot use the paradise colorsheme. i wanna use the paradise color :(

**Comment by Manas140** [comment]
Hmm... are there any errors?

**Comment by anshmendiratta** [comment]
Same problem, but no immediate errors. It looks like this

<img width="1640" alt="image" src="https://github.com/Manas140/Conscious/assets/67623622/836508e3-b786-4382-b2bc-8546a17e70a6">

There is also no Paradise colorscheme to choose from with the command.

<img width="377" alt="image" src="https://github.com/Manas140/Conscious/assets/67623622/6a7fff08-a368-40e9-9dac-2c69356db319">

**Comment by Manas140** [comment]
oh you can't set it like that, you'd have to edit the file `init.lua`

**Comment by AryAntara** [comment]
i had edited init.lua but still use the default color

**Comment by AryAntara** [comment]
> Hmm... are there any errors?

nothing

**Comment by Manas140** [comment]
I'm not certain what the issue is then, it should've worked if you've done all of that properly, try :messages and see for any errors there, try installing/updating all the packages, and if the issue still persists try using another color from the init.lua and lemme know

**Comment by Manas140** [comment]
Closed due to inactivity

**Comment by Manas140** [comment]
Closed due to inactivity

**Comment by RayZ0rr** [comment]
I have the same issue. Followed the instructions in the README but the colorscheme is not loaded and `base16-paradise` doesn't exist

**Comment by RayZ0rr** [comment]
I have opened https://github.com/Manas140/Conscious/pull/10 to fix this

**Comment by AryAntara** [comment]
i tried run the :messages 

just got empty

**Comment by AryAntara** [comment]
![image](https://github.com/Manas140/Conscious/assets/85064978/d24b2f55-96c7-4ad3-b8a8-db828e9ecb28)
i just got error like that when i try run in st terminal,

**Comment by AryAntara** [comment]
That was solved
